mgp25/Instagram-API

src/Instagram.php
src/InstagramRegistration.php

Fix for "Methods with the same name as their class will not be constructors in a future version of PHP." error.

PHP7 Support for deprecated style constructors

---

src/Instagram.php
src/InstagramRegistration.php

**FIRST COMMIT:**
When you use `setUser()` to switch users  and the previous user was logged in, but the current user is not,  `$this->isLoggedIn` should be false.
Which lets this work correctly:
```
$i->setUser($user,$pass);    // switch user
if(!$i->isLoggedIn){         // check if already logged in
$i->login();             // if not, log in
}
```
**SECOND COMMIT**
Adds `setProxy()` function for InstagramRegistration
**THIRD COMMIT**
I forgot to declare the variables for the proxy functions
`$proxy` & `$proxy_auth`

Fix setUser() -> isLoggedIn / Add proxy support for InstagramRegistration / Fix proxy variable declarations

---

src/http/Response/MediaInfoResponse.php
src/http/Response/Response.php

In response to the other pull request...
May be better to update response class with getter/setter for the full response so it can be used in other responses later on if needed. Instead of a one-off function for mediainforesponse()

update Response class with setFullResponse() and getFullResponse(). update mediaInfoResponse() with setFullResponse()

---

src/http/Response/Objects/Item.php

`original_width` was set for Item but `original_height` was always null because it forgotten to set int `__construct` of `Item`.

add missing init for original_height

---

src/Utils/Settings.php

#579 introduced a strange bit of code that pretty much breaks the library in all circumstances. It asks if the data **file** is writable (not the data **path**), despite having just deleted that file in the line above, and disregarding the fact that new installs won't have that file there anyway.
I'm guessing what the submitter was trying to do was check if the `/data` directory is writable, but that requires a small rewrite of the parameters for the constructor of this class. This PR reverts the change to make the library usable again.

Fixing broken code added in #579

---

src/Instagram.php

Using rawurlencode() fails, changed to urlencode().

Fix $query encoding for searchFBLocation

---

src/Instagram.php
src/http/Response/ReelsMediaResponse.php

As mentioned in #806, a response with an associative array.
New endpoint:
- ``feed/reels_media/``
Usage:
```php
$api = new \InstagramAPI\Instagram(false);
// ....
$userList = array('25025320', '189393625');
$result = $api->getReelsMediaFeed($userList);
var_dump($result->reels);
```

Add reels media feed

---

src/InstagramRegistration.php
src/http/Response/AccountCreationResponse.php
src/http/Response/ChallengeResponse.php

Gets rid of this message after a successful registration
```
Your account was successfully created! :)
PHP Notice:  Undefined index: pk in /home/danleyb2/PhpstormProjects/instagramapi-test/vendor/mgp25/instagram-php/src/http/Response/AccountCreationResponse.php on line 35
```
Fixes Issue #820  which is just a warning initializing ChallengeResponse for JsonMapper (there is no `response` parameter passed)

fix `pk` access path, Fix #820

---

src/Instagram.php

The values for `latitude` and `longitude` are sent in the `lat` and `lng` keys from the Instagram server, so I've updated the dynamic methods called to reflect that.

Fixed the method names for location

---

src/Instagram.php

Instagram returns redirect from endpoint 'si/fetch_headers' to 'si/fetch_headers/'
check your logs while login()

endpoint fix

---

src/Instagram.php
src/http/HttpInterface.php

this basically just adds the parameters, but on top of that, enables JSON_BIGINT_AS_STRING in the json_decode function.
The json_decode change is required since the returned next_max_id for the getusertags request is a very long numerical string - without JSON_BIGINT_AS_STRING, the code will convert the ID to int and turn it into an exponential number due to 32bit limitations in ints.

Allow pagination for getUserTags function

---

src/Utils/AdaptImage.php

In some tests I did I could see that the image quality was getting very low.
I then verified that the imagejpeg () function was not set to the maximum quality, when it is set to no value, the default value is 75% of quality.
I changed the function to leave the value at 100%. The gain in quality is visible and makes a big difference in the post.

Maintaining image quality at 100%

---

src/Utils/SettingsAdapter.php

1. fix type for undefined variable in '? options['settings_path']' (missing dollar)
2. rewrite ternary operator with if/else, to avoid questions with associativity

Fix SettingsAdapter for PHP 7

---

examples/usingMemcachedSettingsAdapter.php
src/InstagramRegistration.php
src/Utils/SettingsAdapter.php
src/Utils/SettingsAdapter/Memcached.php
src/Utils/SettingsAdapter/SettingsInterface.php
src/http/HttpInterface.php

This pull request adds ability to create your own settings adapters.
The main rules are
1. Implement `InstagramAPI\SettingsAdapter\SettingsInterface` interface
2. Specify *settingsAdapter* array key **type = custom** and **class = className** of needed adapter;
example:
```
$instagram = new \InstagramAPI\Instagram(true, false, [
'type'  => 'custom',
'class' => \InstagramAPI\SettingsAdapter\Memcached::class
]);
```

Improving settings adapter

---

src/Instagram.php
src/http/HttpInterface.php

Done:
- Refactored the main request() function to be much cleaner and more maintainable.
- Added Guzzle cookie loading/saving support.
- Rewrote HttpInterface constructor to allow Guzzle re-use between multiple setUser calls.
To be done:
- Solve the question of how to handle legacy non-Guzzle cookies.
- Fix various clearly marked TODOs in the code.
- Port all other HttpInterface functions to Guzzle too.

Work in Progress: HttpInterface Guzzle Rewrite!

---

src/Instagram.php
src/http/HttpInterface.php

Removed methods:
- verifyHost()
- verifyPeer()
Added methods:
- setVerifySSL()
- getVerifySSL()

HttpInterface: Migrate SSL verification to Guzzle method

---

src/Instagram.php
src/http/HttpInterface.php

Removed:
- The "proxy" array.
Added:
- setProxy(), which uses the Guzzle proxy format.
- getProxy()

HttpInterface: Migrate Proxying to Guzzle method

---

src/Instagram.php
src/http/HttpInterface.php

- Moved the HttpInterface construction to the Instagram class constructor, since
they belong together very tightly and we now only need one instance of it.
- HttpInterface defaults are now only set once. The user can now be sure that if
they've called setProxy() or setVerifySSL() on the class, those settings will
now be kept even after they change to another user via setUser()!
- Renamed resetInterface() to updateFromSettingsAdapter() to clarify new purpose.
- Revised some work-in-progress comments for CookieJar.

HttpInterface: Preserve proxy and verifySSL values

---

src/http/HttpInterface.php

- Now keeps the HTTPS API connection alive, to save 100-200ms per query.

HttpInterface: Improve request() performance

---

src/Exception/LoginException.php
src/Instagram.php

Hello sir! :)
Recent commit 42beba3134ef9ef9c8b40e56406ba46bba2c94c4
added two factor login but broke the login exception system.
This fix reuses the same method of throwing as in Client.php
which makes proper exceptions thrown at login again, such as:
"Uncaught InstagramAPI\Exception\IncorrectPasswordException:
InstagramAPI\Response\LoginResponse: The password you entered is
incorrect. Please try again."

Fixed bugged login exceptions

---

examples/twoFactorLogin.php
src/Instagram.php

- Reverts 5d8be61e3c8b0e285a6a4ad2222dd879103548e9, since there
was no way for us to always return a LoginResponse.
- Documents return value properly.

login(): Fix and document return value

---

src/Instagram.php
src/Response/CommentFilterKeywordsResponse.php
src/Response/CommentFilterResponse.php
src/Response/CommentFilterSetResponse.php

Instagram has a function, that allows you to hide inappropriate comments. Here is a screenshot of this interface, so you can clearly understand what I'm talking about:
However, I didn't find it implemented in this library. This request adds an ability to use this functionality.
New endpoints are:
**accounts/get_comment_filter/
accounts/get_comment_filter_keywords/
accounts/set_comment_filter/
accounts/set_comment_filter_keywords/**
Unfortunately, I didn't manage how I can ignore SSL pinning on Android, so I used my iPhone to sniff requests. But then I checked all requests with decompiled Android v10.9.0 app source code. And they are completely same.
I can provide all the additional information, if needed.
P.S. If you know anything about bypassing SSL pinning on latest app versions,  pls …

Implement comment blocked-words functionality.

---

src/Client.php
src/Utils.php

This one is for @mgp25.
It seems, device id is no longer used as a multipart boundary. 2265154 replaces it with random string.
Also, it seems there was a bug that forced all uploaded filenames to be `pending_media_*.jpg`. 2f1884a fixes it.

Fixes for multipart requests

---

src/Response/ChallengeResponse.php
src/Response/MediaInfoResponse.php
src/Response/UploadVideoResponse.php

Closes #1316
Some classes had double had double had double ( ;) ) definitions of
$status and $message, even though they were inheriting those properties
from ResponseTrait.
I did a text search of the whole Response folder and removed the extra
$status and $message from any class that uses ResponseTrait. This fixes
the issue!

Fix duplicate response properties

---

devtools/exceptionTest.php
src/Exception/InvalidSmsCodeException.php
src/Exception/ServerMessageThrower.php

Existing detection method that works on human-readable server messages is unreliable. In the same time, almost all server errors contain `error_type` field. So we should use it as additional source to check against.
Also this PR fixes detection for `InvalidUserException` and adds new `InvalidSmsCodeException`. And I used real responses for `exceptionTest` script. I don't have responses for `AccountDisabledException` and `ForcedPasswordResetException` though.

Improve ServerMessageThrower

---

src/Instagram.php
src/Request/Internal.php
src/Request/Timeline.php
src/Response/MsisdnHeaderResponse.php

1. bc97485 splits `syncFeatures()` in two methods and calls them both on experiments refresh.
2. 1547bee adds new methods used in pre-login flow (since 10.24.0). These methods are marked under research and not used for now.
3. 6e2371b updates our most used method `getTimelineFeed()`.

Various improvements

---

src/Realtime.php
src/Realtime/Client/WebSocket.php

Instagram is deprecating its WebSocket client (so-called Telegraph) in favor of MQTT one (is being used by Facebook Messenger for a long time) since 10.26.0.
Fixes #1353.

Realtime: Make WebSocket client optional

---

src/Request.php

It fixes a bug introduced in #1390: although PHP7 allows it, we must use `array_key_exists()` on const arrays.
Thanks to @rudemex for pointing it in #1410.

Do not use isset() on consts

---

src/Request.php
src/Request/Internal.php

It turned out that Guzzle's streams close supplied handles in `__destruct()`, so there is a chance that handle is already has been closed when we are trying to close it. And that leads to `supplied resource is not a valid stream resource` errors.

Check resources before closing them

---

.github/ISSUE_TEMPLATE/bug-report.md
src/Client.php
src/Debug.php
src/Request.php

This pull request adds a few new features to aid with debugging.
* The client class now stores the most recently processed `Request` object.
* Useful for seeing which request fails in an exception try/catch without having to enable debug mode.
* Adds a field in `Client` class: `_lastRequest` which can be modified with `Client#setLastRequest()` and fetched with `Client#getLastRequest()`
* Added `Request#getUrl()`
* You can now have debug logs be sent to a file rather than just the console.
* Can be enabled by setting the `debugLog` static field in the `Debug` class to true.
* The default file location can be changed from `debug.log` to anything else by changing the `debugLogFile` static field in the `Debug` class

Client, Debug, & Request: Debugger improvements 

---

src/Request/Media.php
src/Response/CommentInfosResponse.php

Hello!
I have discovered recently that Instagram uses a separated request to get comments summary.
Added that request to library.
Sorry for abandoned previous pull request. I just don't know how to edit commits and decided to explore that later.

Media: Add getCommentInfos() function
