- examples/registrationTool.php
I guess you missed something. ;-)
> added missing echo and semicolon

- src/Constants.php
- src/Instagram.php
Fixed Microtime Bug / Added new SIGNATURE KEY / Updated Android and Instagram Version
> Microtime Bug / New SIGNATURE KEY / Update Versions

- src/Instagram.php
get feed for given hashtag (via hashtag string) or location (via location ID)
support pagination
> implement getHashtagFeed and getLocationFeed

- src/Instagram.php
> Better DeviceID generation

- src/Instagram.php
Get recent activity of the accounts you follow.
> Implement getFollowingRecentActivity

- src/Instagram.php
Added missing $data array for generateSignature in getProfileData()
> Added missing variable

- src/Instagram.php
Remove your tag from tagged media.
> New feature - Removal of Selftag

- src/Instagram.php
if $upload_id is_null, you will get "Bad request" response
> Fix image upload if $upload_id is null

- src/Instagram.php
> add max id and count for getUserFeed

- src/Instagram.php
Add missing parameter on the deleteComment() function
> Fix missing param issue

- src/Instagram.php
But it supports "min_timestamp" parameter.
> Endpoint for method "getUserFeed" doesn't supports "count" parameter

- src/Instagram.php
Show friendship data - Are you following the user, is the user following you etc.
> New Feature - 'userFriendship'

- src/func.php
I have added documentation for the functions under the file "func.php" for better understanding of the functions.
> added documentation for the func.php file

- src/Instagram.php
Small addition that I found useful
> Allow using max_id when requesting timeline data

- src/Instagram.php
basicly, space (" ") support for location search and fb user search.
> Fix query string based errors on search

- src/Instagram.php
I needed the ability to fetch multiple pages of my liked media. I thought this might be useful for others too.
Thanks for creating and maintaining this! Especially since Instagram implemented this unreasonable API policy.
> Enabled paged fetching of liked media.

- src/Instagram.php
- src/http/HttpInterface.php
> Add direct message text support

- src/http/Response/FollowerResponse.php
- src/http/Response/FollowingResponse.php
- src/http/Response/Objects/FeedAysf.php
- src/http/Response/Objects/Item.php
- src/http/Response/TimelineFeedResponse.php
add verification for empty data
> add verification

- src/Instagram.php
- src/http/Response/CommentResponse.php
- src/http/Response/Objects/Comment.php
Comment api was return raw data. I add maxid and needed objects.
> Comment api added.

- src/http/Response/Objects/Comment.php
There is no media_id in comment added by mistake!
> medi_id removed

- src/http/Response/UsernameInfoResponse.php
is_favorite bulunamadı hatası kapatıldı.
> Undefined Index is_favorite.

- src/http/Response/LocationFeedResponse.php
Warning: Invalid argument supplied for foreach() in /vendor/mgp25/instagram-php/src/http/Response/LocationFeedResponse.php on line 23
> fixing foreach

- src/Instagram.php
- src/http/Response/EditMediaResponse.php
EditMediaResponse was not working. 
Fixed 2 errors.
> Edit media

- src/http/Response/MediaInfoResponse.php
> MadiaInfoResponse fails when comments does not exist in response.

- src/http/Response/Objects/FriendshipStatus.php
> PR for Issue 564

- src/http/Response/CommentResponse.php
- src/http/Response/DiscoverChannelsResponse.php
- src/http/Response/ExploreResponse.php
- src/http/Response/FollowingRecentActivityResponse.php
- src/http/Response/LocationFeedResponse.php
- src/http/Response/MediaCommentsResponse.php
- src/http/Response/TagFeedResponse.php
- src/http/Response/TimelineFeedResponse.php
- src/http/Response/UserFeedResponse.php
- src/http/Response/UsertagsResponse.php
When result smaller than 10 items, nex_max_id param don't exist in response
But status is "OK"!
> fix bug with check key "next_max_id" & fix code style

- examples/challengeSMS.php
- examples/checkpoint.php
- src/ChallengeSMS.php
- src/Instagram.php
- src/InstagramRegistration.php
- src/http/HttpInterface.php
- src/http/Response/FriendshipsShowManyResponse.php
- src/http/Response/Objects/FriendshipStatus.php
- src/http/Response/Objects/User.php
- src/http/Response/Response.php
- src/http/Response/TagRelatedResponse.php
SMS Verification Challenge
Anti-flood wait feature
TagRelated service
FriendshipStatus && Friendships ShowMany services
> SMS Verification + Anti-flood + more

- src/Constants.php
The header value has changed for v9.7.0.
> Update X-IG-Capabilities header for v9.7.0

- src/Instagram.php
- src/Utils/SettingsAdapter.php
- src/Utils/SettingsFile.php
- src/Utils/SettingsMysql.php
- src/http/HttpInterface.php
I added some mysql support to setting and added a settings adapter so in future if we need we can add more supports for settings etc.. 
Also i changed curl cookies to store at database, i will make full documentation if you like to pull.
Thanks.
> Added mysql support to setting

- src/Instagram.php
I don't understand the point of adding the JSONMapper. Kills code readability and introduces bugs like this.
> Fix getUsernameId

- src/Constants.php
New value for for 10.1.0/10.2.0
> Update X-IG-Capabilities header for v10.1.0

- src/Utils/SettingsFile.php
Fixed problem with long paths to the configuration files.
> fix error mkdir()

- src/Instagram.php
- src/http/Response/Objects/Reel.php
- src/http/Response/UserStoryFeedResponse.php
New endpoint:
- ``"feed/user/$userId/story/"``
> Get user story feed

- src/Instagram.php
- src/http/Response/Objects/SavedFeedItem.php
- src/http/Response/SavedFeedResponse.php
New endpoint:
- ``"feed/saved/"``
> Get saved feed

- src/Instagram.php
- src/http/Response/CommentLikeUnlikeResponse.php
Support new endpoints:
- ``"media/$commentId/comment_like/"``
- ``"media/$commentId/comment_unlike/"``
> Like / Unlike a comment

- src/Instagram.php
- src/Utils/Utils.php
With some additional randomness.
> Working code for #823

- src/Instagram.php
- src/http/HttpInterface.php
> Add direct message photos

- src/Instagram.php
- src/http/Response/InsightsResponse.php
- src/http/Response/Objects/Insights.php
New endpoint:
`insights/account_organic_insights`
> Get user insights

- src/Instagram.php
- src/http/Response/MediaInsightsResponse.php
- src/http/Response/Objects/MediaInsights.php
New endpoint:
`insights/media_organic_insights/$media_id`
> get media insights

- src/Instagram.php
New endpoints:
- ``media/$mediaId/disable_comments/``
- ``media/$mediaId/enable_comments/``
> Add disable / enable media comments

- examples/exception.php
- src/InstagramException.php
Want to standardize how Exceptions are thrown and handled here.
> Add exception codes

- src/http/Response/ActivityNewsResponse.php
this hint is used by jsonmapper
> same type as old_stories

- examples/checkpoint.php
- examples/exception.php
- src/Checkpoint.php
- src/Constants.php
- src/Instagram.php
- src/InstagramException.php
- src/InstagramRegistration.php
- src/Utils/SettingsAdapter.php
- src/Utils/SettingsFile.php
- src/Utils/SettingsMysql.php
- src/http/HttpInterface.php
@mgp25 Apologies for the duplicate PR - needed the other branch to access my code quickly on composer.
Also fixed settings / data path to be the default one specified by the repo. You couldn't pass it as an argument for `new Instagram()` or anything, so it wasn't very clear / useful and made the code a little confusing.
> Allow usage of mysql settings adapter through flags or env variables

- src/Checkpoint.php
- src/Constants.php
- src/Instagram.php
- src/InstagramRegistration.php
- src/Utils/SettingsAdapter.php
- src/Utils/SettingsFile.php
- src/Utils/SettingsMysql.php
- src/http/HttpInterface.php
> Fix backwards compatibility issues

- src/Instagram.php
- src/InstagramRegistration.php
- src/http/HttpInterface.php
@mgp25 wasn't able to find a dev branch, but I'm ok if you want to make one and merge this to it
> Check response not null before all JSONMapper calls, throw EMPTY_RESPONSE exception

- src/Utils/SettingsMysql.php
add a last_login column to match file settings.
> Add last_login column to match settingsFile

- src/http/HttpInterface.php
> HttpInterface: Move debugging to separate function

- src/http/Response/ExploreResponse.php
- src/http/Response/FollowingRecentActivityResponse.php
- src/http/Response/Objects/ExploreItem.php
- src/http/Response/Objects/Item.php
- src/http/Response/Objects/Reel.php
- src/http/Response/Objects/Stories.php
- src/http/Response/Objects/StoryLocation.php
- src/http/Response/Objects/TopLive.php
- src/http/Response/Objects/Tray.php
- src/http/Response/Objects/User.php
- src/http/Response/SavedFeedResponse.php
- src/http/Response/UserStoryFeedResponse.php
New properties and new objects in connection with ExploreResponse.
Also added few other properties to Reel.
> Add new properties to response objects

- src/Instagram.php
fbsearch/places supports count parameter. If pass something like 1000 it returns more than 30 items (77 in my tests).
> Add optional count parameter for searchFBLocation

- src/Instagram.php
- src/http/Response/DirectThreadResponse.php
- src/http/Response/Objects/ThreadItem.php
- src/http/Response/Objects/ThreadItemMedia.php
1. Use response for directThread method.
2. Support media (image/video) in thread items.
> Enhance direct threads

- Dockerfile
> Dockerfile typo -- Error response from daemon: Unknown instruction: &&

- src/Response/Model/ActionLog.php
- src/Response/Model/Bold.php
- src/Response/Model/ThreadItem.php
1. List all available item types as constants.
2. Add `ActionLog` model, which is used for `action_log` items.
> ThreadItem Enhancements

- src/Instagram.php
Hi, this will add pagination (`$maxId`) support to `getSavedFeed()`.
> Add pagination support to saved feed

- src/Response/Model/Item.php
This fixes the view count for the getUserStoryFeed() function.
> Fix for story view count.

- composer.json
- src/InstagramID.php
Benefits:
- `toCode()` is about 8x faster now;
- `fromCode()` is about 4x faster now;
- no lookup tables.
> Use GMP functions for shortcode conversions

- src/Instagram.php
This one is for @mgp25.
Basically there is nothing important here: I just replaced deprecated endpoint with new one, and tweaked a param for login experiments call.
> Fix pre-login flow

- README.md
Not really necessary but small changes/additions.
> Small changes to the readme.

- src/Request/Direct.php
- src/Request/Hashtag.php
- src/Request/Live.php
- src/Request/Media.php
Hello, hope you enjoy these fixes! :)
> Various small bugfixes

- src/Realtime.php
> Realtime: Fix namespace issue on some PHP versions

- src/Push.php
Let's leave it open for some time.
> Push: Document some new pushes
